import { useState } from 'react';
import {
  History,
  Repeat,
  ExternalLink,
  User,
  AlertCircle,
  FileCheck2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useRetainerGenerationsList } from '../api/useRetainerGenerations';
import { useRetainerTemplatesList } from '../api/useRetainerTemplates';
import { useUsersList } from '../api/useUsers';
import type { RetainerGenerationAuditDetails } from '../api/types';

export function RetainerGenerationLogs() {
  const [page, setPage] = useState(1);
  const limit = 20;

  const { data: auditResponse, isLoading, error } = useRetainerGenerationsList({ page, limit });
  const { data: templates = [] } = useRetainerTemplatesList();
  const { data: users = [] } = useUsersList();

  const templateMap = new Map(templates.map((t) => [t.id, t.name]));
  const userMap = new Map(users.map((u) => [u.id, u.name]));

  const logs = auditResponse?.data || [];
  const meta = auditResponse?.meta || { total: 0, limit, offset: 0, hasMore: false };

  const totalPages = Math.ceil(meta.total / limit) || 1;

  return (
    <div className="space-y-4" data-testid="retainer-generation-logs-container">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <History className="h-4 w-4 text-purple-600" />
            Retainer Template Generation Audit Trail
          </h3>
          <p className="text-xs text-slate-500 pt-0.5">
            Immutable log of all work requests generated from recurring retainer blueprints.
          </p>
        </div>

        <Badge variant="outline" className="text-xs bg-purple-50 text-purple-700 font-semibold self-start sm:self-center">
          {meta.total} Total Generation{meta.total !== 1 ? 's' : ''}
        </Badge>
      </div>

      {/* Logs Table */}
      <div className="rounded-lg border border-slate-200 bg-white shadow-xs overflow-hidden">
        {isLoading ? (
          <div className="p-8 text-center text-xs text-slate-500 space-y-2">
            <div className="inline-block h-6 w-6 animate-spin rounded-full border-2 border-slate-300 border-t-purple-600" />
            <p>Loading retainer generation audit logs...</p>
          </div>
        ) : error ? (
          <div className="p-8 text-center text-xs text-rose-600 space-y-2">
            <AlertCircle className="h-6 w-6 mx-auto" />
            <p>Failed to load generation logs: {error.message}</p>
          </div>
        ) : logs.length === 0 ? (
          <div className="p-8 text-center text-xs text-slate-500 space-y-1">
            <FileCheck2 className="h-8 w-8 mx-auto text-slate-400" />
            <p className="font-semibold text-slate-700">No generation records found</p>
            <p>Generations triggered from the Operations module or template builder will appear here.</p>
          </div>
        ) : (
          <Table data-testid="generation-logs-table">
            <TableHeader className="bg-slate-50/75">
              <TableRow>
                <TableHead className="w-[50px] text-xs font-semibold text-slate-700">#</TableHead>
                <TableHead className="text-xs font-semibold text-slate-700">Retainer Template</TableHead>
                <TableHead className="text-xs font-semibold text-slate-700">Period Label</TableHead>
                <TableHead className="text-xs font-semibold text-slate-700">Work Request Reference</TableHead>
                <TableHead className="text-xs font-semibold text-slate-700">Generated By (Actor)</TableHead>
                <TableHead className="text-xs font-semibold text-slate-700">Entity</TableHead>
                <TableHead className="text-right text-xs font-semibold text-slate-700">Timestamp</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {logs.map((entry, idx) => {
                const details = (entry.details || {}) as RetainerGenerationAuditDetails;
                const templateName =
                  (details.templateId ? templateMap.get(details.templateId) : null) ||
                  details.templateId ||
                  'Unknown Template';
                const periodLabel = details.periodLabel || 'Ad-Hoc';
                const actorName = userMap.get(entry.userId) || entry.userId;
                const wrId = details.workRequestId || entry.recordId;

                const formattedDate = new Date(entry.createdAt).toLocaleString(undefined, {
                  month: 'short',
                  day: 'numeric',
                  year: 'numeric',
                  hour: '2-digit',
                  minute: '2-digit',
                });

                return (
                  <TableRow
                    key={entry.id}
                    data-testid={`generation-row-${entry.id}`}
                    className="hover:bg-slate-50/50 transition-colors"
                  >
                    <TableCell className="font-mono text-xs text-slate-400">
                      {(page - 1) * limit + idx + 1}
                    </TableCell>

                    <TableCell>
                      <span className="font-semibold text-xs text-slate-900" data-testid={`log-template-${entry.id}`}>
                        {templateName}
                      </span>
                    </TableCell>

                    <TableCell>
                      {details.periodLabel ? (
                        <Badge
                          variant="outline"
                          className="font-mono text-xs py-0.5 px-2 bg-purple-50 text-purple-700 border-purple-200 font-semibold gap-1"
                          data-testid={`log-period-${entry.id}`}
                        >
                          <Repeat className="h-3 w-3" />
                          {periodLabel}
                        </Badge>
                      ) : (
                        <span className="text-xs text-slate-400">None</span>
                      )}
                    </TableCell>

                    <TableCell>
                      <a
                        href={`/operations?search=${wrId}`}
                        className="inline-flex items-center gap-1 font-mono text-xs text-blue-600 hover:text-blue-800 hover:underline"
                        data-testid={`log-wr-${entry.id}`}
                      >
                        <span>{wrId.slice(0, 13)}...</span>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </TableCell>

                    <TableCell>
                      <div className="flex items-center gap-1.5 text-xs text-slate-700">
                        <User className="h-3.5 w-3.5 text-slate-400" />
                        <span>{actorName}</span>
                      </div>
                    </TableCell>

                    <TableCell>
                      <Badge variant="outline" className="text-[10px] py-0 px-1 border-slate-300 bg-slate-100 text-slate-800">
                        {entry.entity}
                      </Badge>
                    </TableCell>

                    <TableCell className="text-right text-xs text-slate-500 whitespace-nowrap">
                      {formattedDate}
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </div>

      {/* Pagination Controls */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between text-xs text-slate-500 pt-2">
          <span>
            Showing {(page - 1) * limit + 1} to {Math.min(page * limit, meta.total)} of {meta.total} generations
          </span>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={page <= 1}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              className="text-xs h-8"
              data-testid="logs-prev-page"
            >
              Previous
            </Button>
            <Button
              variant="outline"
              size="sm"
              disabled={page >= totalPages}
              onClick={() => setPage((p) => p + 1)}
              className="text-xs h-8"
              data-testid="logs-next-page"
            >
              Next
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
